### ISSUE TITLE
Getting "num is not a valid integer" on master builds

### ISSUE THREAD

**Issue by tansanDOTeth** [me-foundation/runestone-lib#70] opened 2024-06-19 04:42 UTC
I was building this master locally to test and found out that this commit https://github.com/me-foundation/runestone-lib/commit/b6048872c8335ac006f0f25a71ec94311831c278 is causing an error that I didn't experience on v1.0.2

Here was the amount that was triggering:

```js
// unallocatedBalance 
{ runeId: { block: 840000, tx: 22 }, amount: 0n }
```

I believe this is the condition causing this error
https://github.com/me-foundation/runestone-lib/blob/b6048872c8335ac006f0f25a71ec94311831c278/src/integer/u128.ts#L47-L49

![CleanShot 2024-06-19 at 13 41 19@2x](https://github.com/me-foundation/runestone-lib/assets/92072158/462905b7-b895-437a-b997-c4127791da2d)

**Comment by tansanDOTeth** [comment] 2024-06-25 12:03
I just noticed more issues when trying to store this into a database.

In this code here, it uses `u128.MAX` which is 
https://github.com/me-foundation/runestone-lib/blob/196617942be49e3497e58704ed70c53bacff07f6/src/indexer/index.ts#L42

https://github.com/me-foundation/runestone-lib/blob/196617942be49e3497e58704ed70c53bacff07f6/src/integer/u128.ts#L24-L32

However, it's typed as BigInt so the `u128.max` (`340282366920938463463374607431768211455`) can exceed the max of a big int.
https://github.com/me-foundation/runestone-lib/blob/196617942be49e3497e58704ed70c53bacff07f6/src/indexer/types.ts#L119-L121

**Comment by summraznboi** [comment] 2024-06-29 03:24
`!Number.isSafeInteger(0n)` shouldn't be reachable since the if type branch would only allow numbers and not bigints into this part of the branch:
https://github.com/me-foundation/runestone-lib/blob/b6048872c8335ac006f0f25a71ec94311831c278/src/integer/u128.ts#L42-L52

**Comment by suatap-alt** [comment] 2024-07-25 14:26
> I was building this master locally to test and found out that this commit [b604887](https://github.com/me-foundation/runestone-lib/commit/b6048872c8335ac006f0f25a71ec94311831c278) is causing an error that I didn't experience on v1.0.2
> 
> Here was the amount that was triggering:
> 
> ```js
> // unallocatedBalance 
> { runeId: { block: 840000, tx: 22 }, amount: 0n }
> ```
> 
> I believe this is the condition causing this error
> 
> https://github.com/me-foundation/runestone-lib/blob/b6048872c8335ac006f0f25a71ec94311831c278/src/integer/u128.ts#L47-L49
> 
> ![CleanShot 2024-06-19 at 13 41 19@2x](https://private-user-images.githubusercontent.com/92072158/340916647-462905b7-b895-437a-b997-c4127791da2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTU5ODcsIm5iZiI6MTcyMTkxNTY4NywicGF0aCI6Ii85MjA3MjE1OC8zNDA5MTY2NDctNDYyOTA1YjctYjg5NS00MzdhLWI5OTctYzQxMjc3OTFkYTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDEzNTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMzQyMjUwMmZkZWJlZTU4ZWY3ODYyN2FhZDQ5YjA0YjUwNzRkMzJlNDE0Yzg2MGNmOTI5N2Y3ZDVmY2NkYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7GLKHOa6z1HFA8nVmsXFO9SI2uBb13iCpZZCTCd2z0g)

The error encountered is not because a BigInt is being validated by `Number.isSafeInteger`.

This error appears to be caused by entering a non-numeric type, such as a string. Implementing a type check to validate that the input is a number or bigint would likely resolve the issue.

**Comment by summraznboi** [comment] 2024-08-16 09:21
@suatap-alt @tansanDOTeth I cannot reproduce this error, closing this out unless a reproducible location or a usable stack trace is provided.

**Closed by summraznboi** 2024-08-16 09:21 UTC
